# Generated by Django 5.2.4 on 2025-08-01 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='afficher_suggestions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(blank=True, choices=[('', 'Je préfère ne pas répondre'), ('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sites_web',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
    ]
